/*
 * CSPAVertexSupport.h - class defintion for Vertex Support
 *
 *
 */

/* Generated by Together */

#ifndef CSPAVERTEXSUPPORT_HPP
#define CSPAVERTEXSUPPORT_HPP

#include "interface_api/IVertexSupport.h"
#include "interface_api/SPAInterface.h"
#include "SPAstlmemory/SPANew.hxx"

class CSPAVertexSupport : public IVertexSupport 
{
public:

    SPA_DECLARE_NEW_DELETE( CSPAVertexSupport )

    static IVertexSupport* createInstance(SPA_TzVertexSupport  &zVertexSupport);

    static IVertexSupport* getInstance();

    static void deleteInstance();

	/**
	 * Get the location of the given vertex
	 * @param int Vertex iId
	 * @param double[3] Vertex Location */
	virtual void getLocation(int iVertexId, double adXYZ[3]);

	virtual int queryAppId(int iVertexId);

protected:

    CSPAVertexSupport(SPA_TzVertexSupport  &zVertexSupport);

    virtual ~CSPAVertexSupport(){}

private:

    static CSPAVertexSupport* m_pzInstance;

	SPA_TzVertexSupport&  m_zVertexSupport;

    // CSPAVertexSupport( const CSPAVertexSupport &X){}

    CSPAVertexSupport& operator= (
        const CSPAVertexSupport &X){ return *this;}

};
#endif //CSPAVERTEXSUPPORT_HPP
